window.CYCLOPS_BALANCE = {
  version: 1,
  currency: "Space Bucks",
  salvagePerCrate: 50,
  tutorial: {
    reserveEnergy: 10,
    firstRecruitCost: 10,
    starterCrateCost: 20,
    firstVoyageBonus: 68,
    completedStage: 12,
  },
  economy: {
    standardCrateCost: 100,
    baseHireCost: 50,
    hireCostStep: 35,
    marketFee: 0.05,
    bucksPerEth: 12000,
    dailyPressTarget: 100,
    starterSessionTargetMinutes: 12,
    longTermSessionTargetMinutes: 20,
  },
  stats: [
    {
      id: "health",
      name: "Health",
      short: "HP",
      battle: "Raises maximum HP and reduces physical damage.",
      crate: "Adds one maximum Energy to the recruit.",
    },
    {
      id: "strength",
      name: "Strength",
      short: "STR",
      battle: "Raises Strength attack damage.",
      crate: "Adds 0.02 Space Bucks per press above 10.",
    },
    {
      id: "dexterity",
      name: "Dexterity",
      short: "DEX",
      battle: "Determines initiative and critical-hit chance.",
      crate: "Raises critical-press chance; critical presses can find Salvage.",
    },
    {
      id: "spirit",
      name: "Spirit",
      short: "SPI",
      battle: "Raises healing and magical defense.",
      crate: "Raises the chance that a press consumes no Energy.",
    },
    {
      id: "sorcery",
      name: "Sorcery",
      short: "SOR",
      battle: "Raises Sorcery attack damage.",
      crate: "Adds 0.02 Space Bucks per press above 10.",
    },
  ],
  races: [
    {
      id: "beast",
      name: "Beast",
      color: "#e38c59",
      sprite: "assets/NormalForward.png",
      bonuses: { health: 0, strength: 2, dexterity: 1, spirit: 0, sorcery: 0 },
      strongAgainst: "magic",
      profile: "Physical hunters with quick reactions. Strong against Magic.",
    },
    {
      id: "magic",
      name: "Magic",
      color: "#8f9cff",
      sprite: "assets/ElementalForward.png",
      bonuses: { health: 0, strength: 0, dexterity: 0, spirit: 1, sorcery: 2 },
      strongAgainst: "metal",
      profile: "Aether-touched beings built around spell pressure. Strong against Metal.",
    },
    {
      id: "metal",
      name: "Metal",
      color: "#b7c3d0",
      sprite: "assets/MetalForward.png",
      bonuses: { health: 1, strength: 1, dexterity: 1, spirit: 0, sorcery: 0 },
      strongAgainst: "wood",
      profile: "Forged generalists with balanced physical traits. Strong against Wood.",
    },
    {
      id: "wood",
      name: "Wood",
      color: "#55ef85",
      sprite: "assets/WoodForward.png",
      bonuses: { health: 0, strength: 0, dexterity: 1, spirit: 2, sorcery: 0 },
      strongAgainst: "stone",
      profile: "Living flora with strong recovery and awareness. Strong against Stone.",
    },
    {
      id: "stone",
      name: "Stone",
      color: "#c5aa74",
      sprite: "assets/StoneForward.png",
      bonuses: { health: 2, strength: 1, dexterity: 0, spirit: 0, sorcery: 0 },
      strongAgainst: "beast",
      profile: "Alien rock-like golems built for endurance. Strong against Beast.",
    },
  ],
  classes: [
    {
      id: "mage",
      name: "Mage",
      bonuses: { health: 0, strength: 0, dexterity: 0, spirit: 1, sorcery: 2 },
      profile: "A magical attacker that favors Sorcery damage and magical pressure.",
    },
    {
      id: "warrior",
      name: "Warrior",
      bonuses: { health: 1, strength: 2, dexterity: 0, spirit: 0, sorcery: 0 },
      profile: "A direct physical attacker with stronger Strength damage and solid endurance.",
    },
    {
      id: "knight",
      name: "Knight",
      bonuses: { health: 2, strength: 1, dexterity: 0, spirit: 0, sorcery: 0 },
      profile: "A defensive fighter with the largest starting HP and Energy profile.",
    },
    {
      id: "shaman",
      name: "Shaman",
      bonuses: { health: 0, strength: 0, dexterity: 0, spirit: 2, sorcery: 1 },
      profile: "A sustain-focused caster with better healing and Energy preservation.",
    },
    {
      id: "rogue",
      name: "Rogue",
      bonuses: { health: 0, strength: 1, dexterity: 2, spirit: 0, sorcery: 0 },
      profile: "A fast physical fighter built around initiative, criticals, and Salvage finds.",
    },
    {
      id: "ranger",
      name: "Ranger",
      bonuses: { health: 0, strength: 1, dexterity: 1, spirit: 1, sorcery: 0 },
      profile: "A flexible scout with physical pressure, speed, and efficient crate work.",
    },
  ],
  rarities: [
    { id: "common", name: "Common", weight: 45, bonusPoints: 0, color: "#92979c" },
    { id: "uncommon", name: "Uncommon", weight: 25, bonusPoints: 1, color: "#55ef85" },
    { id: "rare", name: "Rare", weight: 18, bonusPoints: 2, color: "#5ea9ff" },
    { id: "epic", name: "Epic", weight: 9, bonusPoints: 3, color: "#b879ff" },
    { id: "legendary", name: "Legendary", weight: 3, bonusPoints: 5, color: "#f3c94c" },
  ],
  bayLevels: [
    { level: 0, slots: 0, recoveryPerHour: 0, cost: 0, marks: 0 },
    { level: 1, slots: 1, recoveryPerHour: 3600, cost: 0, marks: 0 },
    { level: 2, slots: 2, recoveryPerHour: 3600, cost: 30, marks: 0 },
    { level: 3, slots: 3, recoveryPerHour: 3600, cost: 175, marks: 0 },
    { level: 4, slots: 4, recoveryPerHour: 3600, cost: 500, marks: 1 },
    { level: 5, slots: 4, recoveryPerHour: 3960, cost: 1200, marks: 3 },
  ],
  trainingModes: [
    {
      id: "light",
      name: "Light",
      gain: 1,
      chance: 1,
      description: "Guaranteed control. Spend 1 TP for +1 selected stat.",
    },
    {
      id: "moderate",
      name: "Moderate",
      gain: 2,
      chance: 0.5,
      description: "A coin flip. Spend 1 TP for a 50% chance at +2.",
    },
    {
      id: "intense",
      name: "Intense",
      gain: 4,
      chance: 0.25,
      description: "High variance. Spend 1 TP for a 25% chance at +4.",
    },
  ],
  combat: {
    maxCareerFights: 10,
    maxTurns: 20,
    careerBuckReward: 12,
    eventDuration: 1000,
    openingDelay: 750,
    raceAdvantage: 1.1,
    criticalMultiplier: 1.5,
    healThreshold: 0.35,
    betweenTournamentRoundHeal: 0.25,
  },
  itemTypes: [
    {
      id: "weapon",
      name: "Weapon",
      stat: "strength",
      variants: [
        ["Crown Visor Blade", "assets/item-concepts-cyclops/individual/relics/crown-visor-artifact.png"],
        ["Button Shrine Maul", "assets/item-concepts-cyclops/individual/relics/miniature-button-shrine.png"],
        ["Mark Tablet Edge", "assets/item-concepts-cyclops/individual/relics/tournament-mark-tablet.png"],
      ],
    },
    {
      id: "armor",
      name: "Armor",
      stat: "health",
      variants: [
        ["Arena Heart Plate", "assets/item-concepts-cyclops/individual/cores/arena-heart-core.png"],
        ["Portal Reactor Shell", "assets/item-concepts-cyclops/individual/cores/portal-reactor-core.png"],
        ["Salvaged Battery Guard", "assets/item-concepts-cyclops/individual/cores/salvaged-visor-battery.png"],
      ],
    },
    {
      id: "scanner",
      name: "Scanner",
      stat: "dexterity",
      variants: [
        ["Gold Targeting Monocle", "assets/item-concepts-cyclops/individual/lenses/gold-targeting-monocle.png"],
        ["Portal Prism Scanner", "assets/item-concepts-cyclops/individual/lenses/portal-prism-lens.png"],
        ["Obsidian Scope", "assets/item-concepts-cyclops/individual/lenses/obsidian-scope-lens.png"],
      ],
    },
    {
      id: "charm",
      name: "Charm",
      stat: "spirit",
      variants: [
        ["Orbital Eye Charm", "assets/item-concepts-cyclops/individual/charms/orbital-eye-charm.png"],
        ["Portal Shard Charm", "assets/item-concepts-cyclops/individual/charms/portal-shard-charm.png"],
        ["Red Visor Pendant", "assets/item-concepts-cyclops/individual/charms/red-visor-pendant.png"],
      ],
    },
    {
      id: "focus",
      name: "Focus",
      stat: "sorcery",
      variants: [
        ["Portal Step Focus", "assets/item-concepts-cyclops/individual/boots/portal-step-greaves.png"],
        ["Tournament Focus", "assets/item-concepts-cyclops/individual/boots/tournament-champion-boots.png"],
        ["Bay Technician Focus", "assets/item-concepts-cyclops/individual/boots/bay-technician-boots.png"],
      ],
    },
  ],
  itemRarities: [
    {
      id: "common",
      name: "Common",
      weight: 45,
      color: "#92979c",
      durability: 100,
      primary: [1, 2],
      sideRolls: 0,
      salvageBase: 4,
      repairFull: 20,
      marketBase: 55,
    },
    {
      id: "uncommon",
      name: "Uncommon",
      weight: 28,
      color: "#55ef85",
      durability: 120,
      primary: [2, 3],
      sideRolls: 1,
      salvageBase: 6,
      repairFull: 30,
      marketBase: 90,
    },
    {
      id: "rare",
      name: "Rare",
      weight: 17,
      color: "#5ea9ff",
      durability: 150,
      primary: [3, 4],
      sideRolls: 1,
      salvageBase: 9,
      repairFull: 45,
      marketBase: 150,
    },
    {
      id: "epic",
      name: "Epic",
      weight: 8,
      color: "#b879ff",
      durability: 200,
      primary: [5, 6],
      sideRolls: 2,
      salvageBase: 14,
      repairFull: 70,
      marketBase: 260,
    },
    {
      id: "legendary",
      name: "Legendary",
      weight: 2,
      color: "#f3c94c",
      durability: 250,
      primary: [7, 9],
      sideRolls: 2,
      salvageBase: 20,
      repairFull: 100,
      marketBase: 450,
    },
  ],
};
